### ISSUE TITLE
Missing Link "Truffle’s documentation here"

### ISSUE THREAD

**Issue by mauriff** [ConsenSys-Academy/Blockchain-Developer-Bootcamp#132]
There is a reference of "_Truffle’s documentation here_ " in section _Introduction to Truffle Suite — Part 2_.

I suppose the link is: https://www.trufflesuite.com/docs/truffle/getting-started/running-migrations

**Comment by ConsenSys-Academy** [comment]
Thanks for catching! Would you like to fix this in a PR?

**Comment by ConsenSys-Academy** [comment]
Was solved by a PR!
