### ISSUE TITLE
Feat: Enable search builtin plugin 

### ISSUE THREAD

**Issue by javierlinked** [ConsenSys-Academy/Blockchain-Developer-Bootcamp#182]
Search functionality is handy :) and is built in in `mkdocs`. 

https://www.mkdocs.org/user-guide/configuration/#search

**Comment by javierlinked** [comment]
I can create a PR.

**Comment by ConsenSys-Academy** [comment]
Thank you for this! Not sure we'll be needing it but will keep your PR open!
