### ISSUE TITLE
EVM curriculum help! Add resources

### ISSUE THREAD

**Issue by ConsenSys-Academy** [ConsenSys-Academy/Blockchain-Developer-Bootcamp#230]
https://twitter.com/bensparks_/status/1513238520575537162

**Comment by ConsenSys-Academy** [comment]
Essentially taking these links and adding them into the course for the EVM [at this section](https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/blob/b3493893e8e98e088bc22fc7d943894c521a16ec/docs/S03-smart-contracts/M1-mental-model/L1-mental-model-sc/index.md)

**Comment by ConsenSys-Academy** [comment]
Also good resources h/t @thedarkjester : https://noxx3xxon.notion.site/noxx3xxon/The-EVM-Handbook-bb38e175cc404111a391907c4975426d

**Comment by thedarkjester** [comment]
> More from @thedarkjester :
> 
> https://noxx.substack.com/p/evm-deep-dives-the-path-to-shadowy-a5f?s=r

I think a good place to start:
https://noxx.substack.com/p/evm-deep-dives-the-path-to-shadowy - the first article

**Comment by Amandasilvbr** [comment]
Hey! If i can, I want to contribute with this issue. Can you explain more about this?

**Comment by ConsenSys-Academy** [comment]
solved with #260
