### ISSUE TITLE
Add Patrick Collin's 32 hour FreeCodeCamp video to Bootcamp

### ISSUE THREAD

**Issue by ConsenSys-Academy** [ConsenSys-Academy/Blockchain-Developer-Bootcamp#253]
https://www.freecodecamp.org/news/learn-blockchain-solidity-full-stack-javascript-development/

Should be added here:

https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/blob/3d3277be2334f29d97624eddf86133cc3205a25d/docs/S00-intro/L6-keeping-up/index.md

And here:
https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/blob/3d3277be2334f29d97624eddf86133cc3205a25d/docs/S03-smart-contracts/M2-solidity/L1-background-context/index.md

**Comment by AMMAR-62** [comment]
Can I take up this issue? if it's not assigned yet!

**Comment by AMMAR-62** [comment]
Hello, I already see Patrick Collins Youtube Channel linked in the S00-Intro/L6-keeping-up doc, should I add it to Learning Paths?? or should I not add it??

**Comment by ConsenSys-Academy** [comment]
@AMMAR-62 You absolutely can!

**Comment by Sidharth004** [comment]
@ConsenSys-Academy  hi ! can I take up this issue ...if it's still open ?

**Comment by ConsenSys-Academy** [comment]
@Sidharth004 yes!

**Comment by Sidharth004** [comment]
Added a PR , do let me know if any more changes to make :-)
