### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by AMMAR-62** [ConsenSys-Academy/Blockchain-Developer-Bootcamp#254]
Link in Intro Learning path not working [Link Here](https://github.com/ConsenSys-Academy/Blockchain-Developer-Bootcamp/blob/staging/docs/S00-intro/L6-keeping-up/index.md?plain=1#L68)

**Comment by ConsenSys-Academy** [comment]
@AMMAR-62 Hey! What's the issue exactly?

**Comment by ConsenSys-Academy** [comment]
Correct link is here: https://mint.ethernautdao.io/

**Comment by kkartik07** [comment]
I have updated the link with the correct one. Please review and merge it.
Thanks.

**Comment by GuiBibeau** [comment]
This is fixed :)
